version: '3.8'

services:
  db:
    image: postgres:15
    container_name: worko_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worko_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - worko_net

  backend:
    build: ./backend
    container_name: worko_backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: worko_db
      DB_PORT: 5432
      JWT_SECRET: clave_super_secreta
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - worko_net

  frontend:
    build: ./frontend
    container_name: worko_frontend
    restart: always
    environment:
      - VITE_API_URL=http://backend:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - worko_net

networks:
  worko_net:
    driver: bridge
